[dev]
  command = "npm run build"
  publish = "client/dist"
  functions = "functions/dist/src"

[[headers]]
  for = "/*.ts"
    [headers.values]
    Content-Type = "application/javascript"

[build]
  command = "npm run build"
  publish = "client/dist"
  functions = "functions/dist/src" 

[functions]
  directory = "functions/"
  included_files = ["src/index.ts"]

