[dev]
  publish = "client/dist"

[production]
  command = "npm run build"
  publish = "client/dist"
  

[functions]
  directory = "functions/dist/netlify/functions"
  included_files = ["actions/index.js"]


