[dev]
  publish = "client/dist"

[build]
  command = "npm run build"
  publish = "client/dist"
  functions = "functions/dist/netlify/functions/actions"


[functions]
  directory = "functions/dist/netlify/functions"
  included_files = ["actions/index.js"]


